Create URI-patterns.md
CIMPLE-project/converter pull request #1
Opened 2023-09-04 13:34 UTC by ypesk

2023-09-04 13:59 UTC, ehrhart requested changes

2023-09-04 13:59 UTC, ehrhart commented on URI-patterns.md
> +This is the documentation of the URI design pattern used by the CIMPLE Knowledge Graph. The following SPARQL query provides the number of instances of each type ([results](https://data.silknow.org/sp
The query URL points to data.silknow.org and the query itself probably needs to be updated

2023-09-04 14:11 UTC, ypesk commented
Edited the query URL to data.cimple.eu

2023-09-04 14:26 UTC, merged

2023-09-05 07:20 UTC, rtroncy commented
The PR has been merged (thanks @ehrhart) but I have some comments:

- The values in the Class column should really be the original ontological concept, e.g. not "Claim reviews" but `schema:ClaimReview`
- I prefer the '-' instead of the '_' in the URL construction (which follows the URI slugification rules) which would mean having as group 'claim-review' for example
- I think it is better to use singular other plural in the URL, following again the REST principles as this means the collection of all objects of type X. Hence, this would mean having: /organization; /entity; /claim; /claim-review
- I would not make two different group for /rating and /original-rating ... but use a single group /rating. The property can already distinguish, I presume, whether the value is a normalized rating or an original one, do we have different properties?

2023-09-05 09:15 UTC, ypesk commented
Thanks for the comments @rtroncy, I will edit the files. What do you think I should specify in the Class column of entities?

2023-09-05 09:31 UTC, rtroncy commented
If the entities are extracted with Spotlight (is this what you meant by DBpedia?) then you can put the top class of the DBpedia ontology, `owl:Thing` (https://dief.tools.dbpedia.org/server/ontology/classes/). If the entities are extracted with another tool (spaCy?) and disambiguated with respect to another KG (e.g. Wikidata?), then similarly, putting the top ontology class.

2023-09-05 09:33 UTC, ypesk commented
For now it's using DBpedia Spotlight, I will put `owl:Thing`. Thanks